-- 게시판 전체 조회( 연번, 아이디, 제목, 등록일(년-월-일), 답글표시)
		SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH",
      READCOUNT, TO_CHAR(REGDATE,'YYYY. MM. DD'),
      REGDATE
      FROM ANSWERBOARD a
      	WHERE DELFLAG ='N'
      ORDER BY REFER DESC, STEP
		
-- 게시판 상세 조회(아이디 제목 내용, 등록) 
		
		SELECT SEQ, ID, TITLE, CONTENT, READCOUNT, DELFLAG, REGDATE
			FROM ANSWERBOARD a
				WHERE SEQ ='1'

-- 게시판 단일/다중삭제
		WHERE REFER = (SELECT REFER FROM ANSWERBOARD a2 WHERE SEQ=#{seq})
		AND STEP >= (SELECT STEP FROM ANSWERBOARD a3 WHERE SEQ=#{seq})
		AND "DEPTH" >= (SELECT "DEPTH" FROM ANSWERBOARD a4 WHERE SEQ=#{seq})
		ORDER BY REFER DESC, STEP
		
